---

- name: Remove ~/.ssh/authorized_keys
  become: true
  ansible.posix.authorized_key:
    user: "{{ svc_user }}"
    key: "{{ svc_user_public_key }}"
    state: absent

- name: Remove service account
  become: true
  ansible.builtin.user:
    name: "{{ svc_user }}"
    group: "{{ svc_group }}"
    uid: "{{ svc_uid }}"
    system: true
    state: absent

- name: Remove group for service account
  when: svc_uid == svc_gid
  become: true
  ansible.builtin.group:
    name: "{{ svc_group }}"
    gid: "{{ svc_gid }}"
    state: absent
